//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversidadesWEB.Pags
{
	public partial class AltaCampus
	{

		/// <summary>
		/// Control form1.
		/// </summary>
		/// <remarks>
		/// Campo generado automáticamente.
		/// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
		/// </remarks>
		protected global::System.Web.UI.HtmlControls.HtmlForm form1;

		/// <summary>
		/// Control ddlInstitucion.
		/// </summary>
		/// <remarks>
		/// Campo generado automáticamente.
		/// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
		/// </remarks>
		protected global::System.Web.UI.WebControls.DropDownList ddlInstitucion;

		/// <summary>
		/// Control tbNombre.
		/// </summary>
		/// <remarks>
		/// Campo generado automáticamente.
		/// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox tbNombre;

		/// <summary>
		/// Control tbDomicilio.
		/// </summary>
		/// <remarks>
		/// Campo generado automáticamente.
		/// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox tbDomicilio;

		/// <summary>
		/// Control tbTelefono.
		/// </summary>
		/// <remarks>
		/// Campo generado automáticamente.
		/// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox tbTelefono;

		/// <summary>
		/// Control ddlCiudad.
		/// </summary>
		/// <remarks>
		/// Campo generado automáticamente.
		/// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
		/// </remarks>
		protected global::System.Web.UI.WebControls.DropDownList ddlCiudad;

		/// <summary>
		/// Control cblCarreras.
		/// </summary>
		/// <remarks>
		/// Campo generado automáticamente.
		/// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
		/// </remarks>
		protected global::System.Web.UI.WebControls.CheckBoxList cblCarreras;

		/// <summary>
		/// Control ddlServicios.
		/// </summary>
		/// <remarks>
		/// Campo generado automáticamente.
		/// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
		/// </remarks>
		protected global::System.Web.UI.WebControls.DropDownList ddlServicios;

		/// <summary>
		/// Control cbCostoExtra.
		/// </summary>
		/// <remarks>
		/// Campo generado automáticamente.
		/// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
		/// </remarks>
		protected global::System.Web.UI.WebControls.CheckBox cbCostoExtra;

		/// <summary>
		/// Control cbDentroCampus.
		/// </summary>
		/// <remarks>
		/// Campo generado automáticamente.
		/// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
		/// </remarks>
		protected global::System.Web.UI.WebControls.CheckBox cbDentroCampus;

		/// <summary>
		/// Control btAgregarServicio.
		/// </summary>
		/// <remarks>
		/// Campo generado automáticamente.
		/// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Button btAgregarServicio;

		/// <summary>
		/// Control gvServicios.
		/// </summary>
		/// <remarks>
		/// Campo generado automáticamente.
		/// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
		/// </remarks>
		protected global::System.Web.UI.WebControls.GridView gvServicios;

		/// <summary>
		/// Control ddlAreas.
		/// </summary>
		/// <remarks>
		/// Campo generado automáticamente.
		/// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
		/// </remarks>
		protected global::System.Web.UI.WebControls.DropDownList ddlAreas;

		/// <summary>
		/// Control TextBox1.
		/// </summary>
		/// <remarks>
		/// Campo generado automáticamente.
		/// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox TextBox1;

		/// <summary>
		/// Control TextBox2.
		/// </summary>
		/// <remarks>
		/// Campo generado automáticamente.
		/// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox TextBox2;

		/// <summary>
		/// Control TextBox3.
		/// </summary>
		/// <remarks>
		/// Campo generado automáticamente.
		/// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox TextBox3;

		/// <summary>
		/// Control btRegistrarArea.
		/// </summary>
		/// <remarks>
		/// Campo generado automáticamente.
		/// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Button btRegistrarArea;

		/// <summary>
		/// Control GridView2.
		/// </summary>
		/// <remarks>
		/// Campo generado automáticamente.
		/// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
		/// </remarks>
		protected global::System.Web.UI.WebControls.GridView GridView2;

		/// <summary>
		/// Control btAlta.
		/// </summary>
		/// <remarks>
		/// Campo generado automáticamente.
		/// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Button btAlta;

		/// <summary>
		/// Control hl1.
		/// </summary>
		/// <remarks>
		/// Campo generado automáticamente.
		/// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HyperLink hl1;
	}
}
