//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversidadesWEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Campus()
        {
            this.CampusArea = new HashSet<CampusArea>();
            this.CampusCarrera = new HashSet<CampusCarrera>();
            this.CampusServicio = new HashSet<CampusServicio>();
        }
    
        public int idCam { get; set; }
        public string nombreCam { get; set; }
        public string domicilio { get; set; }
        public string telefono { get; set; }
        public Nullable<int> idCiu { get; set; }
        public Nullable<int> totalProfes { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampusArea> CampusArea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampusCarrera> CampusCarrera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampusServicio> CampusServicio { get; set; }
    }
}
