//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversidadesWEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampusArea
    {
        public int idCam { get; set; }
        public int idArea { get; set; }
        public Nullable<int> profsLic { get; set; }
        public Nullable<int> profsMa { get; set; }
        public Nullable<int> profsDoc { get; set; }
    
        public virtual AreaAcademica AreaAcademica { get; set; }
        public virtual Campus Campus { get; set; }
    }
}
