//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversidadesWEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampusServicio
    {
        public int idCam { get; set; }
        public int idSer { get; set; }
        public Nullable<short> costoExtra { get; set; }
        public Nullable<short> mismoLugar { get; set; }
    
        public virtual Campus Campus { get; set; }
        public virtual Servicio Servicio { get; set; }
    }
}
