//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversidadesWEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstitucionCarrera
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InstitucionCarrera()
        {
            this.CampusCarrera = new HashSet<CampusCarrera>();
        }
    
        public int idIns { get; set; }
        public int idCar { get; set; }
        public Nullable<short> semestres { get; set; }
        public Nullable<short> creditos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampusCarrera> CampusCarrera { get; set; }
        public virtual Carrera Carrera { get; set; }
        public virtual Institucion Institucion { get; set; }
    }
}
