//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversidadesWEB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UnisEntities : DbContext
    {
        public UnisEntities()
            : base("name=UnisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AreaAcademica> AreaAcademica { get; set; }
        public virtual DbSet<Campus> Campus { get; set; }
        public virtual DbSet<CampusArea> CampusArea { get; set; }
        public virtual DbSet<CampusCarrera> CampusCarrera { get; set; }
        public virtual DbSet<CampusServicio> CampusServicio { get; set; }
        public virtual DbSet<Carrera> Carrera { get; set; }
        public virtual DbSet<Ciudad> Ciudad { get; set; }
        public virtual DbSet<Institucion> Institucion { get; set; }
        public virtual DbSet<InstitucionCarrera> InstitucionCarrera { get; set; }
        public virtual DbSet<Servicio> Servicio { get; set; }
    }
}
